config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :shipper_login, :transporter_login, :nominations
    
    root "shipper_login#index"
     
    get "/shipper", to: "shipper_login#index"
    get "/transporter", to: "transporter_login#index"
    get "/nominations/schedule", to: "nominations#show" 
    get "/dashboard", to: "dashboard#index"
end

app/models/nomination.rb
class Nomination <  ApplicationRecord
end

app/controllers/nominations_controller.rb
require 'net/http'
require 'uri'
require 'json'
require 'date'
class NominationsController < ApplicationController
       if($userRole_frm == "Supplier")
            $user_id = $user_id_supplier
        elsif($userRole_frm == "Transporter")
            $user_id = $user_id_transporter 
        end
    
    def index
        if($userRole_frm == "Supplier")
            $user_id = $user_id_supplier
        elsif($userRole_frm == "Transporter")
            $user_id = $user_id_transporter 
        end
       uri = URI('http://gas-poc4.cfapps.io/GAS/services/viewnomination/')
        http = Net::HTTP.new(uri.host, uri.port)
        req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
        puts $user_id
        req.body = {"userid" => $user_id}.to_json
        res = http.request(req)
        hash_response  = JSON.parse(res.body)
        @nominations = hash_response         
        respond_to do |format|
          format.html  
         format.json  { render :json => @nominations }
        end
    end
    
   def new
        @nomination = ""
        @status = params[:status]
        @capacityRef = params[:capacity_ref]
        @fname = params[:fname]
        @startdate_and_time = params[:startdate_and_time]
        @enddate_and_time = params[:enddate_and_time]
        @injection_point = params[:injection_point]
        @injection_quantity = params[:injection_quantity]
        @offtake_point = params[:offtake_point]
        @offtake_quantity = params[:offtake_quantity]
        @nomination_type = params[:nomination_type]
        @statusNomination = params[:statusNomination]
        @nominationid = params[:nominationid]
        

   end
    
                                 
    def show
        @window = params[:id]
        if(@window == "notification")
            begin
                uri = URI('http://gas-poc4.cfapps.io/GAS/services/viewnotification/')
                http = Net::HTTP.new(uri.host, uri.port)
                req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
                req.body = {"userid" => $user_id.to_i}.to_json 
                res = http.request(req)
                hash_response  = JSON.parse(res.body)
                @notifications = hash_response 
                respond_to do |format|
                    format.html  {render "nominations/notification"}
                    format.json  { render :json => @notifications }
                end
            end
        elsif(@window == "schedule")
             begin
                uri = URI('http://gas-poc4.cfapps.io/GAS/services/viewscheduler/')
                http = Net::HTTP.new(uri.host, uri.port)
                req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
                req.body = { "userid" => "All"}.to_json 
                res = http.request(req)
                
    
                hash_response  = JSON.parse(res.body)
                @newHash={}
                 @splitarr=[]
                
                hash_response.each do |key,value|
                    value.each do |k,v|
                        i=0
                        v.each do |vsche|
                               @splitarr =[]
                           @splitarr<< vsche["date_and_time"].split(" ")
                            @splitarr << vsche["injection_point"] +" - " +vsche["injection_quantity"].to_s 
                            @splitarr << vsche["offtake_point"] +" - " +vsche["offtake_quantity"].to_s
                            @newHash.merge!(i => @splitarr)
                           i=i+1
                        end
                        end
                end
                 
                 puts "newHash"
                 puts @newHash
                 @renderHash = {}
                @renderHashOne ={}
                 @renderHashTwo = {}
                 @renderHashThree ={}
                 @renderHashFour = {}
                
                 j=0
                 @newHash.each do |k,v|
                     time = v[0][1].split(':')
                      @detailsFirst = []
                    @detailsSecond = []
                    @detailsThird = []
                    @detailsFour = []
                        
                           if time[0].to_i >=1 and time[0].to_i <=6
                               @detailsFirst << Date.today.to_s
                               @detailsFirst << "1.00 to 6.00"
                                @detailsFirst << v[1]
                                @detailsFirst << v[2]
                               
                               @renderHashOne.merge!(j => @detailsFirst)
                            elsif time[0].to_i >=7 and time[0].to_i <=12
                               @detailsSecond << Date.today.to_s
                               @detailsSecond << "7.00 to 12.00"
                                @detailsSecond << v[1]
                                @detailsSecond << v[2]
                               @renderHashTwo.merge!(j => @detailsSecond)
                            elsif time[0].to_i >=13 and time[0].to_i <=18
                               @detailsThird << Date.today.to_s
                               @detailsThird << "13.00 to 18.00"
                                @detailsThird << v[1]
                                @detailsThird << v[2]
                               @renderHashThree.merge!(j => @detailsThird)
                            elsif time[0].to_i >=19 and time[0].to_i <=23
                               @detailsFour << Date.today.to_s
                               @detailsFour << "19.00 to 24.00"
                                @detailsFour << v[1]
                                @detailsFour << v[2]
                                @renderHashFour.merge!(j => @detailsFour)
                            end
                        
                j=j+1
                end
                    
                @renderHash.merge!(:one => @renderHashOne)
                @renderHash.merge!(:two => @renderHashTwo)
                @renderHash.merge!(:three => @renderHashThree)
                @renderHash.merge!(:four =>@renderHashFour)
                @schedules = @renderHash   
                respond_to do |format|
                    format.html  {render "nominations/schedule"}
                    format.json  { render :json => @schedules }
                end
            end
        end
        if params[:method] == "execute"
            begin
                uri = URI('http://gas-poc4.cfapps.io/GAS/services/triggerscheduler/')
                http = Net::HTTP.new(uri.host, uri.port)
                req = Net::HTTP::Get.new(uri.path)
                res = http.request(req)
            end
        end
     end
    
    def create
        @startDate = params["nominationstartdate"].to_s+"T"+params["nominationstarttime"]+":00"
        @endDate = params["nominationenddate"].to_s+"T"+params["nominationendtime"]+":00"
        if params[:hiddenStatus] == "Create"
            begin
                
                uri = URI('http://gas-poc4.cfapps.io/GAS/services/addnomination/')
                http = Net::HTTP.new(uri.host, uri.port)
                req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
                req.body = { "startdate_and_time" => @startDate.to_s,
                            "enddate_and_time" =>  @endDate.to_s,
                            "injection_point" => params[:injectionpoint],
                            "injection_quantity" => params[:injectionquantity].to_i,
                            "offtake_point" => params[:offtakepoint],
                            "offtake_quantity" => params[:offtakequantity].to_i,
                            "capacity_ref" => params[:capacity],
                            "status" => "Under Review",
                            "uid" => ($user_id_supplier.to_i)}.to_json 
                res = http.request(req)
                data_hash = JSON.parse(res.body)
                redirect_to :controller => "nominations", :action => "index"  
            end
        elsif params[:hiddenStatus] == "Modify"
        begin                
                uri = URI('http://gas-poc4.cfapps.io/GAS/services/modifynomination/')
                http = Net::HTTP.new(uri.host, uri.port)
                req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
                req.body = {"nominationid" =>params[:hiddenNominationId].to_i,
                            "startdate_and_time" => @startDate.to_s,
                            "enddate_and_time" => @endDate.to_s,
                            "injection_point" => params[:injectionpoint],
                            "injection_quantity" => params[:injectionquantity].to_i,
                            "offtake_point" => params[:offtakepoint],
                            "offtake_quantity" => params[:offtakequantity].to_i,
                            "capacity_ref" => params[:capacity]}.to_json 
                res = http.request(req)
                data_hash = JSON.parse(res.body)
                redirect_to :controller => "nominations", :action => "index"  
            end
           
        end
        
    end       
end

app/helpers/nominations_helper.rb
module NominationsHelper
end

app/views/nominations/new.html.erb
<%= render "layouts/header"  %>

<div class="container-fluid white-container nopad">
      <div class="row">
        <div class="col-sm-3 col-md-1 sidebar">
            <%= render "layouts/sidenav"  %>       
        </div>
        <div class="col-sm-9 col-md-11">        
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 contentheader"> 
            <div class="pull-left"> 
                <% if @status == "createNom" %>
                    <h3 class="pageheading">Create Nomination</h3>
                 <% elsif @status == "modifyNom" %>
                    <h3 class="pageheading">Modify Nomination</h3>
                 <% else %>
                    <h3 class="pageheading">Nomination Details</h3>
                 <% end %>                
            </div>
            <div class="pull-right">
                <% if @status == "createNom" or @status == "modifyNom" %>
                    <%= link_to "<button class='btn btn-primary btn-small'>Back</button>".html_safe, nominations_path %>
                 <% else %>
                     <%= link_to '/nominations/notification' do %>
                        <span class='btn btn-primary btn-small'>Back</span>
                    <% end %>
                 <% end %> 
            </div>              
        </div> 
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-right">  
                 <% if @status == "viewNom" or @status == "modifyNom" %>
                    <span class = "btn btn-success"><%= @nomination_type %></span> <span class = "btn btn-primary"><%= @statusNomination %></span>    
                <% end %>   
            </div>
    
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadmar">                   
       <%= bootstrap_form_for @nomination, url: {action: "create"} do |f| %>
            <% if @status == "modifyNom" or @status == "viewNom" %>
            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 nopadmar">   
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">                   
                    <%= f.text_field :capacity, value: @nominationid, label:"Ref#", disabled: true %>
                </div>
            </div>
            <% end %>
     
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12"> 
                 <% if @status == "viewNom" %>
                    <%= f.text_field :nominationstartdate, value: @startdate_and_time, label:"Nomination Period Start Date", disabled: true %>
                <% elsif @status == "modifyNom" %>
                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 nopadmar"> 
                    <%= f.date_field :nominationstartdate, :value => Time.now.strftime("%Y-%m-%d"), label:"Nomination Period Start Date and Time", required: true %>
                </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 timetopspace"> 
                   <%= f.select :nominationstarttime, [["00", 1], ["01", 2], ["02", 2], ["03", 3], ["04", 4], ["05", 5], ["06", 6], ["07", 7], ["08", 8], ["09", 9], ["10", 10], ["11", 11], ["12", 12], ["13", 13], ["14", 14], ["15", 15], ["16", 16], ["17", 17], ["18", 18], ["19", 19], ["20", 20], ["21", 21], ["22", 22], ["23", 23]], {hide_label: true}  %>
                </div>                  
                
                    <%= f.hidden_field :hiddenNominationId, value: @nominationid %>
                <% else %>
                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 nopadmar"> 
                    <%= f.date_field :nominationstartdate, :value => Time.now.strftime("%Y-%m-%d"), label:"Nomination Period Start Date and Time", required: true %>
                </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 timetopspace"> 
                   <%= f.select :nominationstarttime, [["00", 1], ["01", 2], ["02", 2], ["03", 3], ["04", 4], ["05", 5], ["06", 6], ["07", 7], ["08", 8], ["09", 9], ["10", 10], ["11", 11], ["12", 12], ["13", 13], ["14", 14], ["15", 15], ["16", 16], ["17", 17], ["18", 18], ["19", 19], ["20", 20], ["21", 21], ["22", 22], ["23", 23]], {hide_label: true}  %>
                </div> 
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">  
                <% if @status == "viewNom" %>
                     <%= f.text_field :nominationenddate,  value: @enddate_and_time,label: "Nomination Period End Date", disabled: true %>
                <% elsif @status == "modifyNom" %>
                     <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 nopadmar"> 
                    <%= f.date_field :nominationenddate, :value => Time.now.strftime("%Y-%m-%d"), label:"Nomination Period Start Date and Time", required: true %>
                </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 timetopspace"> 
                   <%= f.select :nominationendtime, [["00", 1], ["01", 2], ["02", 2], ["03", 3], ["04", 4], ["05", 5], ["06", 6], ["07", 7], ["08", 8], ["09", 9], ["10", 10], ["11", 11], ["12", 12], ["13", 13], ["14", 14], ["15", 15], ["16", 16], ["17", 17], ["18", 18], ["19", 19], ["20", 20], ["21", 21], ["22", 22], ["23", 23]], {hide_label: true}  %>
                </div> 
                <% else %>
                   <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 nopadmar"> 
                    <%= f.date_field :nominationenddate, :value => Time.now.strftime("%Y-%m-%d"), label:"Nomination Period Start Date and Time", required: true %>
                </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 timetopspace"> 
                   <%= f.select :nominationendtime, [["00", 1], ["01", 2], ["02", 2], ["03", 3], ["04", 4], ["05", 5], ["06", 6], ["07", 7], ["08", 8], ["09", 9], ["10", 10], ["11", 11], ["12", 12], ["13", 13], ["14", 14], ["15", 15], ["16", 16], ["17", 17], ["18", 18], ["19", 19], ["20", 20], ["21", 21], ["22", 22], ["23", 23]], {hide_label: true}  %>
                </div> 
                <% end %>                    
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">   
                <% if @status == "viewNom" %>
                    <%= f.text_field :injectionpoint, value: @injection_point , label: "Injection Point", disabled: true %>
                <% elsif @status == "modifyNom" %>
                    <%= f.text_field :injectionpoint, value: @injection_point, label: "Injection Point" %>
                <% else %>
                    <%= f.text_field :injectionpoint, label: "Injection Point", required: true %>
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">   
                <% if @status == "viewNom" %>
                    <%= f.text_field :injectionquantity, value: @injection_quantity ,label: "Injection Quantity (in mmbtu)", disabled: true %>
                <% elsif @status == "modifyNom" %>
                    <%= f.text_field :injectionquantity, value: @injection_quantity ,label: "Injection Quantity (in mmbtu)" %>
                <% else %>
                    <%= f.text_field :injectionquantity, label: "Injection Quantity (in mmbtu)", required: true %>
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">  
                <% if @status == "viewNom" %>
                    <%= f.text_field :offtakepoint, Value: @offtake_point, label: "Offtake Point", disabled: true %>
                 <% elsif @status == "modifyNom" %>
                    <%= f.text_field :offtakepoint, Value: @offtake_point, label: "Offtake Point" %>
                <% else %>
                    <%= f.text_field :offtakepoint, label: "Offtake Point", required: true %>
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">  
                <% if @status == "viewNom" %>
                    <%= f.text_field :offtakequantity, Value: @offtake_quantity,label: "Offtake Quantity (in mmbtu)", disabled: true %>
                 <% elsif @status == "modifyNom" %>
                    <%= f.text_field :offtakequantity, Value: @offtake_quantity,label: "Offtake Quantity (in mmbtu)" %>
                <% else %>
                    <%= f.text_field :offtakequantity, label: "Offtake Quantity (in mmbtu)", required: true %>
                <% end %>
            </div>
               <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">   
                <% if @status == "viewNom" %>
                    <%= f.text_field :capacity, Value: @capacityRef,label: "Capacity Right", disabled: true %>
                <% elsif @status == "modifyNom" %>
                <%= f.select :capacity, [["CR101", "CR101"], ["CR102", "CR102"],["CR103", "CR103"],["CR104", "CR104"]], { label: "Capacity Right" }, { class: "selectpicker" }  %>
                <% else %>                    
               <%= f.select :capacity, [["CR101", "CR101"], ["CR102", "CR102"],["CR103", "CR103"],["CR104", "CR104"]], { label: "Capacity Right" }, { class: "selectpicker" }  %>
                <% end %>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">           
                <% if @status == "modifyNom" %>
                    <%= f.submit "Renominate", class: "btn btn-primary btn-top-spacing align-center" %><br><br>
                    <%= f.hidden_field :hiddenStatus, value: "Modify" %>
                <% end %>
                <% if @status == "createNom" %>
                    <%= f.submit "Submit", class: "btn btn-primary btn-top-spacing align-center" %><br><br>
                    <%= f.hidden_field :hiddenStatus, value: "Create" %>
                <% end %>               
            </div>            
        <% end %>
    </div>  
        </div>
      </div>
</div>
<footer>
  <p></p>
  <p></p>
</footer>

app/views/nominations/notification.html.erb
<%= render "layouts/header"  %>

<div class="container-fluid white-container nopad">
      <div class="row">
        <div class="col-sm-3 col-md-1 sidebar">
            <%= render "layouts/sidenav"  %>       
        </div>
        <div class="col-sm-9 col-md-11">  
            <% if ($userRole_frm == "Transporter")  %>  
                <div class="alert alert-danger btn-top-spacing">Transporters don't have permission to access this page</div>
            <% else %>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 contentheader"> 
        <div class="pull-left"> <h3 class="pageheading">Notifications</h3></div>
    </div>
    
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadmar">                   
        <div class="table-responsive">
            <table class="table table-bordered gridTable" id="notification">
            <thead class="gridheader">
                <tr>
                <th>Notification#</th>
                <th>Details</th>
                <th>Action</th>             
             </tr>
            </thead>
            <tbody>                          
                 <% @notifications.each do |key,value| %>
                    <% value.each do |keyNotify,valNotify| %> 
                        <% valNotify.each do |val| %>
                            <% if val["notificationid"] != nil %>
                            <tr>                              
                                <td><%= val["notificationid"] %></td>
                                <td><%= val["notification_details"] %></td>
                                <td class="text-center">
                                    <%= link_to "<span class='glyphicon glyphicon-eye-open'></span>".html_safe, new_nomination_path(status:"viewNom",capacity_ref:val["capacity_ref"],
                                         startdate_and_time:val["startdate_and_time"],
                                         enddate_and_time:val["enddate_and_time"],injection_point:val["injection_point"],
                                         injection_quantity:val["injection_quantity"],offtake_point:val["offtake_point"],
                                         offtake_quantity:val["offtake_quantity"],nomination_type:val["nomination_type"],
                                        statusNomination:val["status"],nominationid:val["nominationid"])  %>
                                </td>
                            </tr>
                            <% end %>
                        <% end %>
                    <% end %>                              
                <% end %>
            </tbody>
          </table>
        </div>
    </div>  
            <%end %>
        </div>
      </div>
</div>
<footer>
  <p></p>
  <p></p>
</footer>

app/views/nominations/schedule.html.erb
<%= render "layouts/header"  %>

<div class="container-fluid white-container nopad">
      <div class="row">
        <div class="col-sm-3 col-md-1 sidebar">
            <%= render "layouts/sidenav"  %>       
        </div>
        <div class="col-sm-9 col-md-11">  
            <% if ($userRole_frm == "Supplier")  %>  
                <div class="alert alert-danger btn-top-spacing">Suppliers don't have permission to access this page</div>
            <% else %>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 contentheader"> 
                    <div class="pull-left"> <h3 class="pageheading">Schedule</h3></div>
               
             <div class="pull-right">
                 <%= link_to :method => :execute  do %>
                        <span class='btn btn-primary btn-small'>Execute Scheduler</span>
                 <% end %>
            </div>      
    
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadmar">                   
                <div class="table-responsive">
                    <table class="table table-bordered gridTable" id="schedule">
                        <thead class="gridheader">
                            <tr>
                                <th class="text-center">Date</th>
                                <th class="text-center">Time Range</th>
                                <th class="text-center">Injection Details</th>
                                <th class="text-center">Offtake Details</th>
                                
                            </tr>
                        </thead>
                        <tbody>  
                        <% if @schedules[:one] != {} %>
                              <% @schedules[:one].each do|k,v| %>
                                <tr>       
                                    <% if v!= nil %>                              
                                        <td><%= v[0] %></td>
                                        <td><%= v[1] %></td>
                                        <td><%= v[2] %></td>
                                        <td><%= v[3] %></td>
                                    <% end %>
                                </tr>
                            <% end %> 
                        <% end %>
                        <% if @schedules[:two] != {} %>
                              <% @schedules[:two].each do|k,v| %>
                                <tr>       
                                    <% if v!= nil %>                              
                                        <td><%= v[0] %></td>
                                        <td><%= v[1] %></td>
                                        <td><%= v[2] %></td>
                                        <td><%= v[3] %></td>
                                    <% end %>
                                </tr>
                            <% end %> 
                        <% end %>
                        <% if @schedules[:three] != {} %>
                              <% @schedules[:three].each do|k,v| %>
                                <tr>       
                                    <% if v!= nil %>                              
                                        <td><%= v[0] %></td>
                                        <td><%= v[1] %></td>
                                        <td><%= v[2] %></td>
                                        <td><%= v[3] %></td>
                                    <% end %>
                                </tr>
                            <% end %> 
                        <% end %>
                             <% if @schedules[:four] != {} %>
                              <% @schedules[:four].each do|k,v| %>
                                <tr>       
                                    <% if v!= nil %>                              
                                        <td><%= v[0] %></td>
                                        <td><%= v[1] %></td>
                                        <td><%= v[2] %></td>
                                        <td><%= v[3] %></td>
                                    <% end %>
                                </tr>
                            <% end %> 
                        <% end %>
                            
                        </tbody>
                    </table>
            </div>
        </div>  
     <%end %>
        </div>
      </div>
</div>
<footer>
  <p></p>
  <p></p>
</footer>